<?php

defined('HOSTCMS') || exit('HostCMS: access denied.');

/**
 * Counter.
 *
 * @package HostCMS
 * @version 6.x
 * @author Hostmake LLC
 * @copyright © 2005-2021 ООО "Хостмэйк" (Hostmake LLC), http://www.hostcms.ru
 */

// Меню формы
$oAdmin_Form_Entity_Menus = Admin_Form_Entity::factory('Menus');

$oCounter = Core_Entity::factory('Site', CURRENT_SITE)->Counters->getByDate('0000-00-00');

$iCounter = !is_null($oCounter) 
	? $oCounter->id
	: 0;

// Элементы меню
$oAdmin_Form_Entity_Menus->add(Admin_Form_Entity::factory('Menu')
	->name(Core::_('Counter.website'))
	->icon('fa fa-globe')
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.website_traffic'))
		->icon('fa fa-bar-chart')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/traffic/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/traffic/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.website_visitors'))
		->icon('fa fa-user-secret')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/visitors/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/visitors/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.referrer'))
		->icon('fa fa-link')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/referrer/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/referrer/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.page'))
		->icon('fa fa-bar-chart')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/page/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/page/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.useragents'))
		->icon('fa fa-desktop')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/useragent/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/useragent/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.counter_variants'))
		->icon('fa fa-th-list')
		->img('/admin/images/images.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/counters/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/counters/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.initial_data'))
		->icon('fa fa-list')
		->img('/admin/images/chart_bar_edit.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/index.php', 'edit', NULL, 0, $iCounter))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/index.php', 'edit', NULL, 0, $iCounter))
	)
)
->add(Admin_Form_Entity::factory('Menu')
	->name(Core::_('Counter.searchsystem'))
	->icon('fa fa-search')
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.searchquery'))
		->icon('fa fa-search')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/searchquery/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/searchquery/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.searchsystem'))
		->icon('fa fa-search')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/searchsystem/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/searchsystem/index.php', NULL, NULL, 0, 0))
	)
)
->add(Admin_Form_Entity::factory('Menu')
	->name(Core::_('Counter.features'))
	->icon('fa fa-cogs')
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.devices'))
		->icon('fa fa-pie-chart')
		->img('/admin/images/chart_pie.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/device/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/device/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.os'))
		->icon('fa fa-pie-chart')
		->img('/admin/images/chart_pie.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/os/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/os/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.browsers'))
		->icon('fa fa-pie-chart')
		->img('/admin/images/chart_pie.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/browser/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/browser/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.displays'))
		->icon('fa fa-pie-chart')
		->img('/admin/images/chart_pie.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/display/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/display/index.php', NULL, NULL, 0, 0))
	)
)
->add(Admin_Form_Entity::factory('Menu')
	->name(Core::_('Counter.crawlers'))
	->icon('fa fa-search')
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.crawler_summary'))
		->icon('fa fa-pie-chart')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/crawler/summary/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/crawler/summary/index.php', NULL, NULL, 0, 0))
	)
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.crawler_pages'))
		->icon('fa fa-file-text-o')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/crawler/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/crawler/index.php', NULL, NULL, 0, 0))
	)
)
->add(Admin_Form_Entity::factory('Menu')
	->name(Core::_('Counter.ip'))
	->icon('fa fa-laptop')
	->add(Admin_Form_Entity::factory('Menu')
		->name(Core::_('Counter.ip'))
		->icon('fa fa-bar-chart')
		->img('/admin/images/chart_bar.gif')
		->href($oAdmin_Form_Controller->getAdminActionLoadHref('/admin/counter/ip/index.php', NULL, NULL, 0, 0))
		->onclick($oAdmin_Form_Controller->getAdminActionLoadAjax('/admin/counter/ip/index.php', NULL, NULL, 0, 0))
	)
);